<style>
	body {
	    font-family:arial;
	    font-size:10pt;
	}
	table td {
	    width:7px;
	}
	table {
	    border-collapse:collapse;
	    border-spacing: 0px;
	    font-size:9pt;
	    width:700px
	}
	.td-border td,
	.te_adicional th, 
	.te_adicional td {
	    border: 1px solid black;
	    padding: 15px 7px;
	}
	.tr-title td {
	    background-color:silver;
	}
	.my-table td {
	    padding:3px;
	    padding-bottom:6px;
	    padding-top:1px;
	    font-size:10pt;
	}
	hr { 
	    display: block;
	    margin-top: 0.4em;
	    margin-bottom: 0.4em;
	    margin-left: auto;
	    margin-right: auto;
	    border-style: inset;
	    border-width: 2px;
	}
	img {
	    width: 103px;
	    height:87px;
	    margin-top: 5px;
	}
</style>

<?php
function mask($val, $mask) {
	$maskared = '';
	$k = 0;
	for ($i = 0; $i<=strlen($mask)-1; $i++) {
		if ($mask[$i] == '#') {
			if(isset($val[$k]))
				$maskared .= $val[$k++];
		} else {
			if (isset($mask[$i]))
				$maskared .= $mask[$i];
		}
	}
	return $maskared;
}
?>
<div style="width:100%;height:5px;">
	<table style="table-layout: fixed;width:100%;">
		<tr>
			<td>
				<center>
					<img src="resources/logo002.png">
				</center>
			</td>
		</tr>
		<tr>
			<td style="font-size:15pt;">
				<b>
					<center>TERMO DE FALTA E AVARIA</center>
				</b>
			</td>
		</tr>
	</table>
</div>
<div style="background-color:#F60;width:100%;height:5px;"></div>
<br>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="50"><span style="font-weight:bold;"><?= $this->razao ?></span></td>
		<?php
			date_default_timezone_set('America/Sao_Paulo');
			$data_atual = date('d/m/Y H:i:s');
		?>
		<td colspan="50" align="right">
			<span style="font-weight:bold;">Data Impressão do Termo: </span><?= $data_atual ?>
		</td>
	</tr>
	<tr>
		<?php
			$cnpj = $this->cnpj;
			$cnpj = mask($cnpj, '##.###.###/####-##');
		?>
		<td colspan="100"><span style="font-weight:bold;">CNPJ: </span><?= $cnpj  ?></td>
	</tr>
	<tr>
		<td colspan="50"><span style="font-weight:bold;">UNIDADE: </span><?= $this->unidade ?></td>
		<td colspan="50" align="right">
			<span style="font-weight:bold;">N° do Termo: </span><?= $this->termo ? $this->termo : "---"; ?>
		</td>
	</tr>
</table>
<hr>
<table>
	<tr>
		<td colspan="100"><span style="font-weight:bold;">Receita Federal:</span></td>
	</tr>
	<tr>
		<td colspan="100"><span style="font-weight:bold;"></span><?= $this->alfandega ? $this->alfandega : "---"; ?></td>
	</tr>
	<tr>
		<td colspan="100"><span style="font-weight:bold;"></span><?= $this->delegacia ? $this->delegacia : "---"; ?></td>
	</tr>
</table>
<hr>
<table>
	<tr>
		<td colspan="100"><span style="font-weight:bold;">DOC.ENTRADA/ANO/Nº </span></td>
	</tr>
	<tr>
		<td colspan="100"><?= "<b>". $this->doc . ":</b>" ?></td>
	</tr>
	<tr>
		<td colspan="100">
			<?php 
				foreach ($this->numero as $numeros) {
					echo $numeros . ' ';
				}
			?>
		</td>
	</tr>
</table>
<hr>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="30">
			<span style="font-weight:bold;">Conhecimento: </span><?= $this->lote_conhec ? $this->lote_conhec : "---"; ?>
		</td>
		<td colspan="35"><span style="font-weight:bold;">Repartição de Origem: </span></td>
		<?php
			if ($this->cesv) {
				$dataHora = implode("/", explode("-", $this->cesv ));
				$dataHora = explode(" ", $dataHora);
				$formato = array_reverse(explode("/", $dataHora[0]));
				$hora = explode(".", $dataHora[1]);	
				$data = $formato[0] . "/" . $formato[1] . "/" . $formato[2] . "  " . $hora[0];		
			}
		?>
		<td colspan="35" align="right"><span style="font-weight:bold;">Data/Hora Entrada Veiculo: <br></span></td>
	</tr>
	<tr>
		<?php
			if ($this->proc_id) {
				$reparticao = $this->proc_id . " " . $this->proc_nome;
			}
		?>
		<td colspan="30"><span style="font-weight:bold;">Lote: </span><?= $this->LOTE_ID ? $this->LOTE_ID : "---"; ?></td>
		<td colspan="35"><span style="font-weight:bold;"></span><?= $reparticao ? $reparticao : "---"; ?></td>
		<td colspan="35" align="right"><span style="font-weight:bold;"></span><?= $data ? $data : "---"; ?></td>
	</tr>
	<tr>
		<td colspan="30">
			<span style="font-weight:bold;">Lote SRF: </span><?= $this->lote_receita ? $this->lote_receita : "---"; ?>
		</td>
		<td colspan="35"></td>
		<td colspan="35" align="right"></td>
	</tr>
</table>
<hr>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="50"><span style="font-weight:bold;">Exp/Imp: </span></td>
		<td colspan="50" align="right"><span style="font-weight:bold;">CNPJ Exp/Imp: </span></td>
	</tr>
	<tr>
		<?php
			$cnpj = $this->cli_cgc;
			if ($cnpj) {
				$cnpj = mask($cnpj, '##.###.###/####-##');
			}
		?>
		<td colspan="50"><span style="font-weight:bold;"></span><?= $this->cli_nome ? $this->cli_nome : "---"; ?></td>
		<td colspan="50" align="right"><span style="font-weight:bold;"></span><?= $cnpj ? $cnpj : "---"; ?></td>
	</tr>
</table>
<hr>
<!-- 
<table style="table-layout: fixed;width:100%;">
	<tr>
		<td colspan="50"><span style="font-weight:bold;">Transportadora: </span></td>
		<td colspan="50" align="right"><span style="font-weight:bold;">CNPJ Transportadora: </span></td>
	</tr>
	<tr>
		<?php
			$cnpj = $this->trans_cgc;
			if ($cnpj) {
				$cnpj = mask($cnpj, '##.###.###/####-##');
			}
			
		?>
		<td colspan="50"><span style="font-weight:bold;"></span><?= $this->trans_nome ? $this->trans_nome : "---"; ?></td>
		<td colspan="50" align="right"><span style="font-weight:bold;"></span><?= $cnpj ? $cnpj : "---"; ?></td>
	</tr>
</table>
<hr>
-->
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="35">
			<span style="font-weight:bold;">Qtde./Espécie Declarada: </span>
			<?= $this->lote_vol_dec ? $this->lote_vol_dec . " Vo" : "---"; ?>
		</td>
		<td colspan="35">
			<span style="font-weight:bold;">Qtde./Espécie Física: </span>
			<?= $this->lote_vol_fisico ? $this->lote_vol_fisico . " Vo" : "---"; ?>
		</td>
		<td colspan="35" align="right">
			<span style="font-weight:bold;">Peso Declarado: </span>
			<?= $this->lote_peso_bruto ? $this->lote_peso_bruto . " Kg" : "---"; ?>
		</td>
	</tr>
	<!-- 
	<tr>
		<td colspan="50" align="right">
			<span style="font-weight:bold;">Peso Físico: </span>
			<?= $this->lote_peso_fisico ? $this->lote_peso_fisico . " Kg" : "---"; ?>
		</td>
	</tr>
	-->
</table>
<hr>
<?php foreach ($this->teste as $i => $item) { ?>
	<div style="background-color:#A9A9A9;; width:100%; height:5px;">
		<table style="table-layout: fixed;width:100%;">
			<?php
				if ($item['TAS_QTD']) {
					$qtd_vol_avariado = $item['TAS_QTD'] . " " . $item['ESP_ID'];
				}
			?>
			<tr>
				<td colspan="25">
					<span style="font-weight:bold;">Qtde Vol. Avariado:</span>
					<?= $qtd_vol_avariado ? $qtd_vol_avariado : "---"; ?>
				</td>
				<td colspan="25">
					<span style="font-weight:bold;">Item: </span>
					<?= $item['OITEM_ID'] ? $item['OITEM_ID'] : "---"; ?>
				</td>
				<td colspan="25">
					<span style="font-weight:bold;">Container: </span>
					<?= $item['CNT_ID'] ? $item['CNT_ID'] : "---"; ?>
				</td>
				<td style="text-align: right;" colspan="25">
					<span style="font-weight:bold;">Veiculo: </span>
					<?= $item['VEICULO'] ? $item['VEICULO'] : "---"; ?>
				</td>
			</tr>
			<tr>
				<td colspan="50">
					<span style="font-weight:bold;">Obs.: </span>
				</td>
				<td style="text-align: right;" colspan="50">
					<span style="font-weight:bold;">Reboque: </span>
					<?= $this->vei_id_rbq ? $this->vei_id_rbq : "---"; ?>
				</td>
			</tr>
		</table>
	</div>
	<table style="table-layout: fixed;width:100%;">
		<tr>
			<td colspan="100">
				<?php $desc_avarias = $this->desc_avarias; ?>
				<?php if ($desc_avarias[$i]['tas_id'] == $item['TAS_ID']) { ?>
					<?php echo $desc_avarias[$i]['tas_id'] . ' ) '; ?>
					<?php foreach ($desc_avarias[$i]['desc_avarias'] as $desc_avaria) { ?>
						<?php echo $desc_avaria['AVA_DESCRICAO'] . ', '; ?>
					<?php } ?>
				<?php } ?>
			</td>
		</tr>
	</table>
<?php } ?>
<hr>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<!--
		<td colspan="30">
			<?php 
				foreach ($this->veiculo as $veiculos) {
					echo "<b>Veiculo:</b> " . $veiculos . '<br>';
				}
			?>
		</td>
		<td colspan="35">
			<?php 
				foreach ($this->reboque as $reboques) {
					echo "<b>Reboque:</b> " . $reboques . '<br>';
				}
			?>
		</td>
		-->
		<td colspan="35" style="text-align: center; color: #696969;">
			<?php 
				// foreach ($this->reboque as $reboques) {
				echo "VEICULO DEVIDAMENTE LACRADO<br>";
				// }
			?>
		</td>
	</tr>
</table>
<hr>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="100">
			<span style="font-weight:bold;">OBSERVAÇÕES: </span>
		</td>
	</tr>
	<tr>
		<td colspan="100">
			<span style="font-weight:bold;"></span><?= $this->ter_obs ? $this->ter_obs : "---"; ?>
		</td>
	</tr>
</table>
<hr>
<!--
<div style="table-layout: fixed; width: 100%;">
 	<ul style="list-style-type: none;">
		<?php $list_files = glob("//barra-apl01/SARA/OrdemServico/". $this->OS_ID ."/FOTOS/*.*"); ?>
		<?php foreach ($list_files as $list_file) { ?>
			<?php $extension = substr($list_file, -3); ?>
			<?php if ($extension !== '.db') { ?>
				<li style="float: left; width: 30%; text-align: center;">
					<?php echo '<img src="'. $list_file .'" height="212" width="400" />'; ?>
				</li>
			<?php } ?>
		<?php } ?>
	</ul>
</div>
-->
<!-- //barra-apl01/SARA/OrdemServico/". $this->OS_ID ."/FOTOS/TFA/lote/*.* -->
<table style="table-layout:fixed;width:100%;">
	<tr>
		<?php $list_files = glob("//barra-apl01/SARA/OrdemServico/". $this->OS_ID ."/TFA". $this->LOTE_ID ."/*.*"); ?>
		<?php $cont = 0; ?>
		<?php foreach ($list_files as $list_file) { ?>
			<?php $extension = substr($list_file, -3); ?>
			<?php if ($extension !== '.db') { ?>
				<td style="width:30%;text-align:center;">
					<?php echo '<img src="'. $list_file .'" height="500" width="500" />'; ?>
				</td>
				<?php 
				$cont++; 
				if ($cont == 4) { echo '<tr>'; $cont = 0; } 
				?>
			<?php } ?>
		<?php } ?>
	</tr>
</table>
<br>

<div class="te_adicional">
	<?php if ($this->excel_observacao) { ?>
		<?php echo $this->excel_observacao; ?>
		<br>
		<hr>
	<?php } ?>
</div>

<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="50">
			<span style="font-weight:bold;">Conferente: </span>
			<?= $this->ass_nome ? $this->ass_nome : "---"; ?>
		</td>
		<td colspan="50" align="right">
			<span style="font-weight:bold;">Motorista: </span>
			<?= $this->pes_nome ? $this->pes_nome : "---"; ?>
		</td>
	</tr>
	<tr>
		<td colspan="50">
			<span style="font-weight:bold;">Fiel Depositario: </span>
			<?= $this->sis_fieldeposita ? $this->sis_fieldeposita : "---"; ?>
		</td>
		<td colspan="50" align="right">
			<?php 
				$cpf = $this->pes_cpf;
				$cpf = mask($cpf,'###.###.###-##');
			?>
			<span style="font-weight:bold;">CPF Motorista: </span>
			<?= $cpf ? $cpf : "---"; ?>
		</td>
	</tr>
</table>
<br>
<br>
<table style="table-layout:fixed;width:100%;">
	<tr>
		<td colspan="50"></td>
	</tr>
	<tr>
		<td colspan="50" align="right">
			<span style="font-weight:bold;">Assinatura: </span>
			<?= "______________________________________"; ?>
		</td>
	</tr>
</table>