alert("cookie: " + (typeof document.cookie !== "undefined" ? 'Yes' : 'No'))
alert("onbeforeunload: " + (typeof window.onbeforeunload !== "undefined" ? 'Yes' : 'No'))
alert("navigator: " + (typeof window.navigator !== "undefined" ? 'Yes' : 'No'))
alert("- onLine: " + (typeof window.navigator.onLine !== "undefined" ? 'Yes' : 'No'))
alert("addEventListener: " + (typeof window.addEventListener !== "undefined" ? 'Yes' : 'No'))
alert("referrer: " + (typeof document.referrer !== "undefined" ? 'Yes' : 'No'))
alert("history: " + (typeof window.history !== "undefined" ? 'Yes' : 'No'))
alert("- back(): " + (typeof window.history.back !== "undefined" ? 'Yes' : 'No'))
alert("- go(): " + (typeof window.history.go !== "undefined" ? 'Yes' : 'No'))
