A EMPRESA: <?= $this->NOME_CLIENTE ?><br />
Você esta recebendo a Nota Fiscal de Serviços Eletrônica Número <?= $this->NUM_NFSE ?><br />
<br />
<br />
Segue anexo boleto e demonstrativo referente a esta Nota Fiscal de Serviços Eletrônica (NFS-e)<br />
<br />
Em caso de dúvidas, entre em contato com financeiro@barradorio.com.br<br />
<br />
<br />
<strong>"Solicito que a conferência das notas emitidas ocorram num prazo máximo de 48 horas. 
Após este período não será mais aceito reclamações."</strong>
<br />
<br />
Atenciosamente,<br />
Barra do Rio Terminal Portuário S/A<br />
www.barradorio.com.br<br />