<?php

use Phinx\Seed\AbstractSeed;

class Menus extends AbstractSeed
{
    public function run()
    {
        $data = array(
            array(
                "id" => 1,
                "titulo" => "Dashboard",
                "ordem" => 1,
                "nivel" => 1,
                "controller" => "Pages",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"material-icons\">home</i>",
                "menu_id" => NULL,
            ),
            array(
                "id" => 2,
                "titulo" => "Empresas",
                "ordem" => 3,
                "nivel" => 2,
                "controller" => "Empresas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"material-icons\">apartment</i>",
                "menu_id" => 30,
            ),
            array(
                "id" => 3,
                "titulo" => "Financeiro",
                "ordem" => 6,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-dollar-sign\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 18,
                "titulo" => "Estruturas Armazenagem",
                "ordem" => 1,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-warehouse\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 19,
                "titulo" => "Áreas",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "Areas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-road fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 20,
                "titulo" => "Endereços",
                "ordem" => 2,
                "nivel" => 2,
                "controller" => "Enderecos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-location-arrow fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 21,
                "titulo" => "Estoques",
                "ordem" => 3,
                "nivel" => 2,
                "controller" => "Estoques",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-institution fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 22,
                "titulo" => "Estoque Endereços",
                "ordem" => 4,
                "nivel" => 2,
                "controller" => "EstoqueEnderecos",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-location-arrow\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 23,
                "titulo" => "Etiqueta Produtos",
                "ordem" => 5,
                "nivel" => 2,
                "controller" => "EtiquetaProdutos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-tags fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 24,
                "titulo" => "Funcionalidades",
                "ordem" => 2,
                "nivel" => 2,
                "controller" => "Funcionalidades",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-wrench fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 25,
                "titulo" => "Locais",
                "ordem" => 7,
                "nivel" => 2,
                "controller" => "Locais",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-compass fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 26,
                "titulo" => "Ncms",
                "ordem" => 8,
                "nivel" => 2,
                "controller" => "Ncms",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-list-ol fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 27,
                "titulo" => "Produtos",
                "ordem" => 9,
                "nivel" => 2,
                "controller" => "Produtos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-cubes fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 28,
                "titulo" => "Tipo de Estruturas",
                "ordem" => 3,
                "nivel" => 2,
                "controller" => "TipoEstruturas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-institution fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 29,
                "titulo" => "Unidade de Medidas",
                "ordem" => 11,
                "nivel" => 2,
                "controller" => "UnidadeMedidas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fa fa-balance-scale fa-fw\" aria-hidden=\"true\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 30,
                "titulo" => "Acesso",
                "ordem" => 1,
                "nivel" => 1,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-user-lock\"></i>",
                "menu_id" => NULL,
            ),
            array(
                "id" => 31,
                "titulo" => "WMS Alfandegado",
                "ordem" => 2,
                "nivel" => 1,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-plane\"></i>",
                "menu_id" => NULL,
            ),
            array(
                "id" => 32,
                "titulo" => "Cadastros",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 18,
            ),
            array(
                "id" => 34,
                "titulo" => "Documentação de Entrada",
                "ordem" => 2,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-file-invoice\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 35,
                "titulo" => "Operacional",
                "ordem" => 4,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-cubes\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 36,
                "titulo" => "Aduaneiro",
                "ordem" => 5,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fab fa-adn\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 37,
                "titulo" => "Controle de Portaria",
                "ordem" => 3,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-truck\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 38,
                "titulo" => "Consultas e Relatorios",
                "ordem" => 7,
                "nivel" => 2,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-search\"></i>",
                "menu_id" => 31,
            ),
            array(
                "id" => 39,
                "titulo" => "Cadastros ",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 34,
            ),
            array(
                "id" => 40,
                "titulo" => "Processos",
                "ordem" => 2,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 34,
            ),
            array(
                "id" => 41,
                "titulo" => "Cadastros ",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 35,
            ),
            array(
                "id" => 42,
                "titulo" => "Processos",
                "ordem" => 2,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 35,
            ),
            array(
                "id" => 43,
                "titulo" => "Cadastros ",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 36,
            ),
            array(
                "id" => 44,
                "titulo" => "Processos ",
                "ordem" => 2,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 36,
            ),
            array(
                "id" => 45,
                "titulo" => "Cadastros ",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 3,
            ),
            array(
                "id" => 46,
                "titulo" => "Processos ",
                "ordem" => 2,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 3,
            ),
            array(
                "id" => 47,
                "titulo" => "Cadastros",
                "ordem" => 1,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 37,
            ),
            array(
                "id" => 48,
                "titulo" => "Processos",
                "ordem" => 2,
                "nivel" => 3,
                "controller" => "",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 37,
            ),
            array(
                "id" => 49,
                "titulo" => "Áreas",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "Areas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 50,
                "titulo" => "Locais",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "Locais",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 51,
                "titulo" => "Funcionalidades",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "funcionalidades",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 52,
                "titulo" => "Tipo de Estruturas",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "tipo-estruturas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 53,
                "titulo" => "Endereços",
                "ordem" => 5,
                "nivel" => 4,
                "controller" => "enderecos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 32,
            ),
            array(
                "id" => 54,
                "titulo" => "Tipo de Documentos",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "tipo-documentos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 55,
                "titulo" => "Tratamento de Cargas",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "tratamentos-cargas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 56,
                "titulo" => "Moedas",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "moedas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 57,
                "titulo" => "Cotação de Moedas",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "moedas-cotacoes",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 58,
                "titulo" => "Regimes Aduaneiros",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "regimes-aduaneiros",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 59,
                "titulo" => "Naturezas de Carga",
                "ordem" => 5,
                "nivel" => 4,
                "controller" => "naturezas-cargas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 39,
            ),
            array(
                "id" => 60,
                "titulo" => "Documento de Entrada",
                "ordem" => 6,
                "nivel" => 4,
                "controller" => "documentacao-entrada",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 40,
            ),
            array(
                "id" => 61,
                "titulo" => "Operacoes",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "operacoes",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 62,
                "titulo" => "Portarias",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "portarias",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 63,
                "titulo" => "Veículos",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "veiculos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 64,
                "titulo" => "Transportadoras",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "transportadoras",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 65,
                "titulo" => "Pessoas",
                "ordem" => 5,
                "nivel" => 4,
                "controller" => "pessoas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 66,
                "titulo" => "Modais",
                "ordem" => 6,
                "nivel" => 4,
                "controller" => "modais",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 47,
            ),
            array(
                "id" => 67,
                "titulo" => "Controle de Chegada",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "documentacao-entrada",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 48,
            ),
            array(
                "id" => 68,
                "titulo" => "Controle de Coletas",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "coletas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 48,
            ),
            array(
                "id" => 69,
                "titulo" => "Tipos de ordens de Servico",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "ordem-servico-tipos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 41,
            ),
            array(
                "id" => 70,
                "titulo" => "Tipos de Avarias",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "avarias",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 41,
            ),
            array(
                "id" => 71,
                "titulo" => "Tipos de Embalagens",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "embalagens",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 41,
            ),
            array(
                "id" => 72,
                "titulo" => "OS Pendentes - Descarga",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "ordens-servico-pendentes",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 42,
            ),
            array(
                "id" => 73,
                "titulo" => "Movimentação de Estoque",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "movimentacoes-estoques",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 42,
            ),
            array(
                "id" => 74,
                "titulo" => "Canais",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "canais",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 43,
            ),
            array(
                "id" => 75,
                "titulo" => "A.F.T.N.S",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "aftns",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 43,
            ),
            array(
                "id" => 76,
                "titulo" => "Liberação Documental",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "liberacoes-documentais",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 44,
            ),
            array(
                "id" => 77,
                "titulo" => "Tipos de Pagamento",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "tipo-pagamentos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 78,
                "titulo" => "Formas de Pagamentos",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "forma-pagamentos",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 79,
                "titulo" => "Bancos",
                "ordem" => 3,
                "nivel" => 4,
                "controller" => "bancos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 80,
                "titulo" => "Baixa Manual",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "faturamento-baixas",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 46,
            ),
            array(
                "id" => 81,
                "titulo" => "Usuários",
                "ordem" => 1,
                "nivel" => 2,
                "controller" => "usuarios",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 30,
            ),
            array(
                "id" => 82,
                "titulo" => "Perfis",
                "ordem" => 2,
                "nivel" => 2,
                "controller" => "perfis",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 30,
            ),
            array(
                "id" => 83,
                "titulo" => "Informativos",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "informativos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 30,
            ),
            array(
                "id" => 84,
                "titulo" => "Menus",
                "ordem" => 5,
                "nivel" => 2,
                "controller" => "menus",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 30,
            ),
            array(
                "id" => 85,
                "titulo" => "Operadores",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "operadores",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 86,
                "titulo" => "Campos do Sistemas",
                "ordem" => 5,
                "nivel" => 4,
                "controller" => "sistema-campos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 87,
                "titulo" => "Tipos de Valores",
                "ordem" => 6,
                "nivel" => 4,
                "controller" => "tipos-valores",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 88,
                "titulo" => "Tipos de Faturamentos",
                "ordem" => 7,
                "nivel" => 4,
                "controller" => "tipos-faturamentos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 89,
                "titulo" => "Tabelas de Preço",
                "ordem" => 8,
                "nivel" => 4,
                "controller" => "tabelas-precos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 45,
            ),
            array(
                "id" => 90,
                "titulo" => "Servicos",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "servicos",
                "action" => "index",
                "params" => "",
                "url" => "",
                "icon" => " <i class=\"fas fa-table\"></i>",
                "menu_id" => 41,
            ),
            array(
                "id" => 91,
                "titulo" => "OS Pendentes - Carga",
                "ordem" => 1,
                "nivel" => 4,
                "controller" => "ordens-servico-pendentes",
                "action" => "index-carga",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-building\"></i>",
                "menu_id" => 42,
            ),
            array(
                "id" => 92,
                "titulo" => "Faturamento",
                "ordem" => 2,
                "nivel" => 4,
                "controller" => "faturamentos",
                "action" => "",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-table\"></i>",
                "menu_id" => 46,
            ),
            array(
                "id" => 93,
                "titulo" => "Gerar OS Interna",
                "ordem" => 4,
                "nivel" => 4,
                "controller" => "ordem-servicos",
                "action" => "gerar-interna",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-warehouse\"></i>",
                "menu_id" => 42,
            ),
            array(
                "id" => 94,
                "titulo" => "Os Pendentes - Internas",
                "ordem" => 5,
                "nivel" => 4,
                "controller" => "ordem-servicos",
                "action" => "internas-pendentes",
                "params" => "",
                "url" => "",
                "icon" => "<i class=\"fas fa-warehouse\"></i>",
                "menu_id" => 42,
            ),
        );        

        $this->execute('SET FOREIGN_KEY_CHECKS=0;');

        $table = $this->table('menus');
        $table->insert($data)->save();
        $this->execute('SET FOREIGN_KEY_CHECKS=1;');
    }
}
